module.exports={
auth:require("./auth.routes"),
channel:require('./channel.routes'),
comment:require('./comment.routes'),
jobOffer:require('./job_offer.routes'),
post:require('./post.routes'),
profile:require('./profile.routes'),
reaction:require('./reactions.routes'),
user:require('./user.routes'),
search:require('./search.routes')
}