module.exports={
  User:require("./User"),
  Channel:require("./Channel"),
  Comment:require("./Comment"),
  JobOffer:require('./JobOffer'),
  Post:require('./Post'),
  User:require('./User'),
  Reaction:require("./Reaction"),
  TokenRecover:require("./TokenRecover"),
  IsRead:require("./IsRead")
}