module.exports={
  User:require("./User"),
  Channel:require("./Channel"),
  Comment:require("./Comment"),
  Job_offer:require('./Job_offer'),
  Post:require('./Post'),
  TokenRecover:require('./TokenRecover'),
  User:require('./User')
}