export const herramientas = [
  "HTML",
  "CSS",
  "Figma",
  "AdobeXD",
  "Framer X",
  "Photoshop",
  "Illustrator",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "Go",
  "Vue.js",
  "Next.js",
  "React",
  "React Native",
  "Angular",
  "Jest",
  "Selenium",
  "Node.js",
  "Express.js",
  "Deno",
  "GraphQL",
  "Koa",
  // {key:'1', value:'HTML'},
  // {key:'2', value:'CSS'},
  // {key:'3', value:'Figma'},
  // {key:'4', value:'AdobeXD'},
  // {key:'6', value:'Photoshop'},
  // {key:'7', value:'Illustrator'},
  // {key:'8', value:'JavaScript'},
  // {key:'9', value:'TypeScript'},
  // {key:'10', value:'Python'},
  // {key:'11', value:'Java'},
  // {key:'12', value:'Go'},
  // {key:'13', value:'Vue.js'},
  // {key:'14', value:'Next.js'},
  // {key:'15', value:'React'},
  // {key:'16', value:'React Native'},
  // {key:'17', value:'Angular'},
  // {key:'18', value:'Jest'},
  // {key:'19', value:'Selenium'},
  // {key:'20', value:'Node.js'},
  // {key:'21', value:'Express.js'},
  // {key:'22', value:'Deno'},
  // {key:'23', value:'GraphQL'},
  // {key:'24', value:'Koa'},
];
