tags:
    - name: Comments
      description: Comments endpoints
paths:
    /api/comment/new/{id}/{scope}:
        post:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description:
                      The mongo id of the document where will make a comment
                - in: params
                  name: scope
                  schema:
                      type: string
                      enum:
                          - joboffer
                          - post
                          - comment
                  required: true
                  description: The place where will make a comment
            summary:
                Create a new comment in specific post, job offer or reply
                another comment
            tags: [Comments]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new_comment'
            responses:
                201:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                comment_success:
                                    $ref: '#/components/examples/comment_success'
                404:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                comment_error_inexistent:
                                    $ref: '#/components/examples/comment_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/comment/edit/{id}:
        put:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description: The id of the comment to update
            summary: Edit a comment made by the logged user
            tags: [Comments]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/edit_comment'
            responses:
                201:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                comment_edit_success:
                                    $ref: '#/components/examples/comment_edit_success'
                401:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                comment_error_unauthorized:
                                    $ref: '#/components/examples/comment_error_unauthorized'
                404:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                comment_error_inexistent:
                                    $ref: '#/components/examples/comment_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/comment/delete/{id}:
        put:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description: The id of comment to delete
            summary: Delete a comment made by the logged user
            tags: [Comments]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                comment_delete_success:
                                    $ref: '#/components/examples/comment_delete_success'
                401:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                comment_error_unauthorized:
                                    $ref: '#/components/examples/comment_error_unauthorized'
                404:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                comment_error_inexistent:
                                    $ref: '#/components/examples/comment_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/comment/admdelete/{id}:
        put:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description: The id of comment to delete
            summary: Delete any comment
            tags: [Admins]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                comment_delete_success:
                                    $ref: '#/components/examples/comment_delete_success'
                404:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                comment_error_inexistent:
                                    $ref: '#/components/examples/comment_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
