tags:
    name: Job Offers
    description: Job Offer endpoints
paths:
    /api/job-offer/new:
        post:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
            summary: Create a new job offer
            tags: [Admins]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new_joboffer'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                joboffer_success:
                                    $ref: '#/components/examples/joboffer_success'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/job-offer/edit/{id}:
        put:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description: The id of offer to update
            summary: Update a job offer
            tags: [Admins]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/edit_joboffer'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                joboffer_edit_success:
                                    $ref: '#/components/examples/joboffer_edit_success'
                404:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                joboffer_error_inexistent:
                                    $ref: '#/components/examples/joboffer_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/job-offer/{id}:
        delete:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description: The id of offer to delete
            summary: Delete a job offer
            tags: [Admins]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                joboffer_delete_success:
                                    $ref: '#/components/examples/joboffer_delete_success'
                404:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                joboffer_error_inexistent:
                                    $ref: '#/components/examples/joboffer_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/job-offer/postulate/{id}:
        post:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                  required: true
                  description: The id of offer to postulate
            summary: Postulate to a job offer
            tags: [Job Offers]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                joboffer_delete_success:
                                    $ref: '#/components/examples/joboffer_delete_success'
                400:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                joboffer_error_selected:
                                    $ref: '#/components/examples/joboffer_error_selected'
                404:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_inexistent:
                                    $ref: '#/components/examples/user_error_inexistent'
                                joboffer_error_inexistent:
                                    $ref: '#/components/examples/joboffer_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/job-offer/all?from={from}&to={to}:
        get:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: query
                  name: from
                  schema:
                      type: number
                  description: Select the first offer
                - in: query
                  name: to
                  schema:
                      type: number
                  description: Select the last offer
            summary: Get all offers
            tags: [Job Offers]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                joboffer_all_success:
                                    $ref: '#/components/examples/joboffer_all_success'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
