tags:
    - name: Users
      description: Users endpoints
    - name: Admins
      description: Only for admin users endpoints
    - name: SERVER
      description: Server endpoints
paths:
    /api/user/all:
        get:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
            summary: Get all the users
            tags: [Admins]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                user_success_all:
                                    $ref: '#/components/examples/user_success_all'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/user/{id}:
        get:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description: The id of the other user
            summary: Get a user
            tags: [Users]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                other_user_success:
                                    $ref: '#/components/examples/other_user_success'
                400:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_inexistent:
                                    $ref: '#/components/examples/user_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
        put:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description: The id of the user
            summary: Modify a user
            tags: [Admins]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                update_user_success:
                                    $ref: '#/components/examples/update_user_success'
                400:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_inexistent:
                                    $ref: '#/components/examples/user_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
    /api/user/favorite/{scope}/{id}:
        put:
            parameters:
                - in: header
                  name: x-token
                  schema:
                      type: string
                  required: true
                  description: The token users account
                - in: params
                  name: scope
                  schema:
                      type: string
                      enum: ['post', 'joboffer']
                  required: true
                  description: Can be post or joboffer
                - in: params
                  name: id
                  schema:
                      type: string
                      format: id
                  required: true
                  description: The id of the other user
            summary: Mark a post as favorite
            tags: [Users]
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/success'
                            examples:
                                favorite_success:
                                    $ref: '#/components/examples/favorite_success'
                400:
                    description: Request error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                favorite_error_inexistent:
                                    $ref: '#/components/examples/favorite_error_inexistent'
                500:
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                user_error_general:
                                    $ref: '#/components/examples/user_error_general'
