export const LOGIN_USER_PENDING="LOGIN_USER_PENDING"
export const LOGIN_USER_REJECTED="LOGIN_USER_REJECTED"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"

export const LOGOUT_USER="LOGOUT_USER"


export const CAMBIADOR = "CAMBIADOR";