export const EDIT_PERSONAL_INFO_PENDING = "EDIT_PERSONAL_INFO_PENDING";
export const EDIT_PERSONAL_INFO_REJECTED = "EDIT_PERSONAL_INFO_REJECTED";
export const EDIT_PERSONAL_INFO_SUCCESS = "EDIT_PERSONAL_INFO_SUCCESS";
export const UPDATE_IMG_USER = "UPDATE_IMG_USER";
