export const GET_SKILLS_PENDING = "GET_SKILLS_PENDING";
export const GET_SKILLS_REJECTED = "GET_SKILLS_REJECTED";
export const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";

export const EDIT_SKILLS_PENDING = "EDIT_SKILLS_PENDING";
export const EDIT_SKILLS_REJECTED = "EDIT_SKILLS_REJECTED";
export const EDIT_SKILLS_SUCCESS = "EDIT_SKILLS_SUCCESS";
